/** @type {import("eslint").Linter.Config} */
module.exports = {
	env: {
		jest: true,
		node: true,
	},
	extends: ["airbnb/base", "plugin:ava/recommended", "plugin:unicorn/recommended", "plugin:@stylistic/disable-legacy"],
	plugins: ["ava", "unicorn", "@stylistic"],
	reportUnusedDisableDirectives: true,
	rules: {
		"array-callback-return": ["error", { allowImplicit: true }],
		"class-methods-use-this": "off",
		"func-names": ["error", "never"],
		"global-require": "off",
		"import/extensions": ["error", "ignorePackages"],
		"import/no-anonymous-default-export": "error",
		"import/no-duplicates": ["error", { considerQueryString: true, "prefer-inline": true }],
		"import/order": ["error", { "newlines-between": "always" }],
		"import/prefer-default-export": "off",
		"no-await-in-loop": "off",
		"no-console": "off",
		"no-implicit-coercion": "error",
		"no-negated-condition": "error",
		"no-param-reassign": "off",
		"no-plusplus": ["error", { allowForLoopAfterthoughts: true }],
		"no-restricted-exports": ["error", { restrictedNamedExports: ["then"] }],
		"no-restricted-syntax": "off",
		"no-return-assign": ["error", "always"],
		"no-underscore-dangle": "off",
		"no-unsafe-optional-chaining": "error",
		"no-unused-vars": ["error", { args: "after-used", ignoreRestSiblings: true, vars: "all", varsIgnorePattern: "^_" }],
		"no-use-before-define": ["error", { functions: false }],
		"prefer-destructuring": "off",
		"prefer-regex-literals": "error",
		"require-await": "error",
		"unicorn/consistent-destructuring": "error",
		"unicorn/no-array-callback-reference": "off",
		"unicorn/no-nested-ternary": "off",
		"unicorn/no-null": "off",
		"unicorn/prefer-switch": ["error", { emptyDefaultCase: "do-nothing-comment" }],
		"unicorn/prevent-abbreviations": "off",
		"@stylistic/function-paren-newline": ["error", "consistent"],
		"@stylistic/indent": ["error", "tab", { SwitchCase: 1 }],
		"@stylistic/max-len": ["error", { code: 130, tabWidth: 2, ignoreUrls: true, ignoreRegExpLiterals: true, ignoreStrings: true, ignoreTemplateLiterals: true }],
		"@stylistic/no-mixed-operators": "error",
		"@stylistic/no-multiple-empty-lines": ["error", { max: 1 }],
		"@stylistic/padding-line-between-statements": ["error", { blankLine: "always", prev: "multiline-block-like", next: "*" }],
		"@stylistic/quotes": ["error", "double"],
		"@stylistic/space-before-function-paren": ["error", { anonymous: "always", named: "never", asyncArrow: "always" }],
		"@stylistic/wrap-iife": ["error", "inside", { functionPrototypeMethods: true }],
	},
};
