module.exports = {
	env: {
		es2020: true,
		es6: true,
		jest: true,
		node: true,
	},
	parserOptions: {
		ecmaVersion: 2020,
		sourceType: "module",
	},
	extends: ["airbnb/base", "plugin:unicorn/recommended"],

	plugins: ["unicorn"],
	rules: {
		"global-require": "off",
		indent: ["error", "tab"],
		"max-len": ["error", { code: 150, tabWidth: 2 }],
		"no-await-in-loop": "off",
		"no-console": "off",
		"no-nested-ternary": "off",
		"no-param-reassign": "off",
		"no-restricted-syntax": "off",
		"no-return-assign": "off",
		"no-tabs": "off",
		"no-underscore-dangle": "off",
		"no-unused-vars": ["error", { vars: "all", args: "after-used", ignoreRestSiblings: true, varsIgnorePattern: "^_" }],
		"no-use-before-define": "off",
		"object-curly-newline": "off",
		"prefer-destructuring": "off",
		quotes: ["error", "double"],
		"array-callback-return": ["error", { allowImplicit: true }],
		"no-multiple-empty-lines": ["error", { max: 1 }],
		"import/order": ["error", { "newlines-between": "always" }],
		"unicorn/filename-case": "off",
		"unicorn/prevent-abbreviations": "off",
		"unicorn/no-nested-ternary": "off",
		"unicorn/no-null": "off",
		"unicorn/no-fn-reference-in-iterator": "off",
		"unicorn/no-reduce": "off",
		"unicorn/import-index": ["error", { ignoreImports: true }],
	},
};
