module.exports = {
	env: {
		es6: true,
		jest: true,
		node: true,
		es2017: true,
		es2020: true,
		es2021: true,
	},
	parserOptions: {
		ecmaVersion: 2021,
		sourceType: "module",
	},
	extends: ["airbnb/base", "plugin:unicorn/recommended"],
	plugins: ["unicorn"],
	rules: {
		"array-callback-return": ["error", { allowImplicit: true }],
		"class-methods-use-this": "off",
		"func-names": ["error", "never"],
		"global-require": "off",
		"import/order": ["error", { "newlines-between": "always" }],
		indent: ["error", "tab"],
		"max-len": ["error", { code: 150, tabWidth: 2 }],
		"no-await-in-loop": "off",
		"no-console": "off",
		"no-implicit-coercion": "error",
		"no-multiple-empty-lines": ["error", { max: 1 }],
		"no-nested-ternary": "off",
		"no-param-reassign": "off",
		"no-restricted-syntax": "off",
		"no-return-assign": ["error", "always"],
		"no-plusplus": ["error", { allowForLoopAfterthoughts: true }],
		"no-tabs": "off",
		"no-underscore-dangle": "off",
		"no-unused-vars": ["error", { args: "after-used", ignoreRestSiblings: true, vars: "all", varsIgnorePattern: "^_" }],
		"no-use-before-define": "off",
		"object-curly-newline": "off",
		"prefer-destructuring": "off",
		quotes: ["error", "double"],
		"space-before-function-paren": ["error", { anonymous: "always", named: "never", asyncArrow: "always" }],
		"unicorn/filename-case": "off",
		"unicorn/import-index": ["error", { ignoreImports: true }],
		"unicorn/no-fn-reference-in-iterator": "off",
		"unicorn/no-nested-ternary": "off",
		"unicorn/no-null": "off",
		"unicorn/no-reduce": "off",
		"unicorn/prefer-flat-map": "error",
		"unicorn/prevent-abbreviations": "off",
		"wrap-iife": ["error", "inside", { functionPrototypeMethods: true }],
	},
};
