name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: ⎔ Setup pnpm
        uses: pnpm/action-setup@v5

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 25
          registry-url: "https://registry.npmjs.org"

      - name: 🚀 Release to npm
        run: pnpm publish --no-git-checks

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 25
          registry-url: "https://npm.pkg.github.com"
          scope: "@iamnapo"

      - name: 🏗 Run replace-in-file
        run: pnpx replace-in-file "eslint-config-iamnapo" "@iamnapo/eslint-config-iamnapo" package.json

      - name: 🚀 Release to GitHub
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
